# Generated by Django 4.1.3 on 2022-11-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_delete_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='role description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_1', models.TextField(blank=True, max_length=100, null=True, verbose_name='task 1')),
                ('task_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='task 2')),
                ('task_3', models.TextField(blank=True, max_length=100, null=True, verbose_name='task 3')),
                ('task_4', models.TextField(blank=True, max_length=100, null=True, verbose_name='task 4')),
                ('task_5', models.TextField(blank=True, max_length=100, null=True, verbose_name='task 5')),
                ('task_6', models.TextField(blank=True, max_length=100, null=True, verbose_name='task 6')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
