# Generated by Django 4.1.3 on 2022-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='task_1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='task 1'),
        ),
        migrations.AddField(
            model_name='role',
            name='task_2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='task 2'),
        ),
        migrations.AddField(
            model_name='role',
            name='task_3',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='task 3'),
        ),
        migrations.AddField(
            model_name='role',
            name='task_4',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='task 4'),
        ),
        migrations.AddField(
            model_name='role',
            name='task_5',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='task 5'),
        ),
        migrations.AddField(
            model_name='role',
            name='task_6',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='task 6'),
        ),
    ]
