# Generated by Django 4.1.3 on 2022-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_userrole_day1_userrole_day1_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='day1',
            field=models.CharField(blank=True, choices=[('tuesday', 'Tuesday'), ('friday', 'Friday'), ('wednesday', 'Wednesday'), ('thurday', 'Thursday'), ('saturday', 'Saturday'), ('monday', 'Monday')], max_length=15, null=True, verbose_name='monday'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day2',
            field=models.CharField(blank=True, choices=[('tuesday', 'Tuesday'), ('friday', 'Friday'), ('wednesday', 'Wednesday'), ('thurday', 'Thursday'), ('saturday', 'Saturday'), ('monday', 'Monday')], max_length=15, null=True, verbose_name='tuesday'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day3',
            field=models.CharField(blank=True, choices=[('tuesday', 'Tuesday'), ('friday', 'Friday'), ('wednesday', 'Wednesday'), ('thurday', 'Thursday'), ('saturday', 'Saturday'), ('monday', 'Monday')], max_length=15, null=True, verbose_name='wednesday'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day4',
            field=models.CharField(blank=True, choices=[('tuesday', 'Tuesday'), ('friday', 'Friday'), ('wednesday', 'Wednesday'), ('thurday', 'Thursday'), ('saturday', 'Saturday'), ('monday', 'Monday')], max_length=15, null=True, verbose_name='thurday'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day5',
            field=models.CharField(blank=True, choices=[('tuesday', 'Tuesday'), ('friday', 'Friday'), ('wednesday', 'Wednesday'), ('thurday', 'Thursday'), ('saturday', 'Saturday'), ('monday', 'Monday')], max_length=15, null=True, verbose_name='friday'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day6',
            field=models.CharField(blank=True, choices=[('tuesday', 'Tuesday'), ('friday', 'Friday'), ('wednesday', 'Wednesday'), ('thurday', 'Thursday'), ('saturday', 'Saturday'), ('monday', 'Monday')], max_length=15, null=True, verbose_name='saturday'),
        ),
    ]
