# Generated by Django 4.1.3 on 2023-07-29 12:57

from django.db import migrations, models
import django.db.models.deletion
import lab_services.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Labs', '0012_alter_issue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found_Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to=lab_services.models.found_item_photo_upload)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('date_found', models.DateField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labs.lab')),
            ],
        ),
    ]
