# Generated by Django 4.1.3 on 2023-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_item',
            name='time_found',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
