# Generated by Django 4.1.3 on 2023-01-02 17:42

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_alter_organization_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='item name')),
                ('pic', models.ImageField(upload_to=assets.models.photo_upload, verbose_name=' asset image')),
                ('status', models.CharField(choices=[('Borrowed', 'Borrowes'), ('Available', 'Available')], max_length=50, verbose_name='asset status')),
                ('condition', models.CharField(choices=[('Faulty', 'Flauty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='lob / organisatioin')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Borrowd_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persion', models.CharField(max_length=50, verbose_name='borrowers name(one)')),
                ('email', models.CharField(max_length=50, verbose_name='borrowers contact')),
                ('location_of_use', models.CharField(max_length=50, verbose_name='Class/Hall')),
                ('picked_on', models.DateTimeField(auto_now=True, verbose_name='date and time picked')),
                ('returned_on', models.DateTimeField(editable=False, verbose_name='date and time returned')),
                ('returned', models.BooleanField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='borrowed item')),
            ],
            options={
                'verbose_name': 'Borrowd_Asset',
                'verbose_name_plural': 'Borrowd_Assets',
            },
        ),
    ]
