# Generated by Django 4.1.3 on 2023-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Faulty', 'Faulty'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='borrowd_asset',
            name='returned_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='date and time returned'),
        ),
    ]
