# Generated by Django 4.1.3 on 2023-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_rename_persion_borrowd_asset_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', ' Not available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
    ]
