# Generated by Django 4.1.3 on 2023-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_asset_condition_alter_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowd_asset',
            old_name='email',
            new_name='contacts',
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Not Woking', 'Not Working'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),
        ),
    ]
