# Generated by Django 4.1.3 on 2023-01-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_rename_email_borrowd_asset_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowd_asset',
            old_name='name',
            new_name='asset',
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Faulty', 'Faulty'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Not available', ' Not available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='borrowd_asset',
            name='returned_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date and time returned'),
        ),
    ]
