# Generated by Django 4.1.3 on 2023-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_alter_borrowd_asset_options_alter_asset_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Borrowed', 'Borrowed'), ('Available', 'Available')], max_length=50, verbose_name='asset status'),
        ),
    ]
