# Generated by Django 4.1.3 on 2022-11-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_account_id_account_account_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization name')),
                ('scale', models.CharField(choices=[('personal venture', 'personal venture'), ('medium scale', 'medium scale'), ('Small scale', 'Small scale')], max_length=50, verbose_name='Scale of organization')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name="Organization's creater")),
            ],
        ),
    ]
