# Generated by Django 4.1.3 on 2022-11-04 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_id_account_account_uuid'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Organization's ID")),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization name')),
                ('scale', models.CharField(choices=[('personal venture', 'personal venture'), ('medium scale', 'medium scale'), ('Small scale', 'Small scale')], max_length=50, verbose_name='Scale of organization')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name="Organization's creater")),
            ],
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
