# Generated by Django 4.1.3 on 2022-12-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0002_alter_organization_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='scale',
            field=models.CharField(choices=[('medium scale', 'medium scale'), ('personal venture', 'personal venture'), ('Small scale', 'Small scale')], max_length=50, verbose_name='Scale of organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name="Organization's creater"),
        ),
    ]
