# Generated by Django 4.1.3 on 2022-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_delete_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='scale',
            field=models.CharField(choices=[('medium scale', 'medium scale'), ('personal venture', 'personal venture'), ('Small scale', 'Small scale')], max_length=50, verbose_name='Scale of organization'),
        ),
    ]
