# Generated by Django 4.1.3 on 2022-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='scale',
            field=models.CharField(choices=[('Small scale', 'Small scale'), ('medium scale', 'medium scale'), ('personal venture', 'personal venture')], max_length=50, verbose_name='Scale of organization'),
        ),
    ]
