# Generated by Django 4.1.3 on 2023-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_organization_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=150, verbose_name='issue details')),
                ('reported_on', models.DateTimeField(verbose_name='date reported')),
                ('status', models.CharField(choices=[('medium scale', 'medium scale'), ('Small scale', 'Small scale'), ('personal venture', 'personal venture')], max_length=50, verbose_name='state')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-reported_on'],
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='scale',
            field=models.CharField(choices=[('medium scale', 'medium scale'), ('Small scale', 'Small scale'), ('personal venture', 'personal venture')], max_length=50, verbose_name='Scale of organization'),
        ),
    ]
