# Generated by Django 4.1.3 on 2023-01-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_remove_organization_scale_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Argent', 'Argent')], max_length=50, verbose_name='state'),
        ),
    ]
