# Generated by Django 4.1.3 on 2023-01-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_alter_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='reported_by',
        ),
    ]
