# Generated by Django 4.1.3 on 2023-06-07 11:23

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('Labs', '0003_alter_issue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='item name')),
                ('pic', models.ImageField(upload_to=assets.models.asset_photo_upload, verbose_name=' asset image')),
                ('status', models.CharField(choices=[('Borrowed', 'Borrowed'), ('Not available', ' Not available'), ('Available', 'Available')], max_length=50, verbose_name='asset status')),
                ('condition', models.CharField(choices=[('Faulty', 'Faulty'), ('Not Woking', 'Not Working'), ('Good', 'Good')], max_length=50, verbose_name='asset condition')),
                ('Lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labs.lab', verbose_name='lab / Lab')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Borrowed_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='borrowers name(one)')),
                ('contacts', models.CharField(max_length=50, verbose_name='borrowers contact')),
                ('location_of_use', models.CharField(max_length=50, verbose_name='Class/Hall')),
                ('picked_on', models.DateTimeField(editable=False, verbose_name='date and time picked')),
                ('returned_on', models.DateTimeField(blank=True, null=True, verbose_name='date and time returned')),
                ('returned', models.BooleanField()),
                ('Lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labs.lab', verbose_name='lab')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_asset', to='assets.asset', verbose_name='borrowed item')),
                ('issued_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_asset_issued_out', to='accounts.account', verbose_name='issued out by')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_asset_receiver', to='accounts.account', verbose_name='received by')),
            ],
            options={
                'verbose_name': 'Borrowd Asset',
                'verbose_name_plural': 'Borrowd Assets',
                'ordering': ['returned_on'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('HDMI Cables', 'HDMI Cables'), ('Others', 'Others'), ('VGA Cables', 'VGA Cables'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Projector', 'Projector')], max_length=50, verbose_name='Asset category name')),
                ('category_pic', models.ImageField(blank=True, null=True, upload_to=assets.models.asset_categorty_photo_upload, verbose_name='Category image')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='number of assets available')),
                ('working_quantity', models.PositiveIntegerField(default=0, verbose_name='number is assets that are working')),
                ('borrowed_assets', models.PositiveIntegerField(default=0, verbose_name='number is assets that are borrowedd')),
                ('Lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Labs.lab', verbose_name='lab / Lab')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory', verbose_name='asset type'),
        ),
    ]
