# Generated by Django 4.1.3 on 2023-07-29 08:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Not available', ' Not available'), ('Available', 'Available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Others', 'Others'), ('HDMI Cables', 'HDMI Cables'), ('Extension/Power Cables', 'Extension/Power Cables'), ('Projector', 'Projector'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Remote', 'Remote'), ('VGA Cables', 'VGA Cables')], max_length=50, verbose_name='Asset category name'),
        ),
        migrations.AlterField(
            model_name='borrowed_asset',
            name='contacts',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='borrowers contact'),
        ),
    ]
