# Generated by Django 4.1.3 on 2023-02-02 08:17

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorty_name', models.TextField(choices=[('Others', 'Others'), ('Projector', 'Projector'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('HDMI Cables', 'HDMI Cables'), ('VGA Cables', 'VGA Cables')], max_length=50, verbose_name='Asset category name')),
                ('categoty_pic', models.ImageField(upload_to=assets.models.asset_categorty_photo_upload, verbose_name='Category image')),
                ('quantity', models.PositiveIntegerField(verbose_name='number of assets available')),
                ('woring_quantity', models.PositiveIntegerField(verbose_name='number is assets that are working')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Available', 'Available'), ('Not available', ' Not available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory', verbose_name=''),
        ),
    ]
