# Generated by Django 4.1.3 on 2023-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_lab_id_borrowed_asset_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Others', 'Others'), ('VGA Cables', 'VGA Cables'), ('Projector', 'Projector'), ('HDMI Cables', 'HDMI Cables'), ('VGA-HDMI Converters', ' VGA-HDMI Converters')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
