# Generated by Django 4.1.3 on 2023-02-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_issue_status'),
        ('assets', '0002_assetcategory_alter_asset_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategory',
            name='categorty_name',
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='lab / organization'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Not Woking', 'Not Working'), ('Faulty', 'Faulty'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),
        ),
    ]
