# Generated by Django 4.1.3 on 2023-07-29 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_condition_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed_asset',
            name='picked_on',
        ),
        migrations.AddField(
            model_name='borrowed_asset',
            name='time_picked_on',
            field=models.TimeField(default=django.utils.timezone.now, editable=False, verbose_name='time picked'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending Approval', 'Pending Approval'), ('Borrowed', 'Borrowed'), ('Not available', ' Not available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('VGA Cables', 'VGA Cables'), ('Extension/Power Cables', 'Extension/Power Cables'), ('Projector', 'Projector'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Others', 'Others'), ('HDMI Cables', 'HDMI Cables'), ('Remote', 'Remote')], max_length=50, verbose_name='Asset category name'),
        ),
        migrations.AlterField(
            model_name='borrowed_asset',
            name='returned_on',
            field=models.TimeField(blank=True, null=True, verbose_name='date and time returned'),
        ),
    ]
