# Generated by Django 4.1.3 on 2023-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_condition_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Not available', ' Not available'), ('Pending Approval', 'Pending Approval'), ('Available', 'Available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('VGA Cables', 'VGA Cables'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('HDMI Cables', 'HDMI Cables'), ('Extension/Power Cables', 'Extension/Power Cables'), ('Projector', 'Projector'), ('Others', 'Others'), ('Remote', 'Remote')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
