# Generated by Django 4.1.3 on 2023-07-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_borrowed_asset_picked_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Not Woking', 'Not Working'), ('Faulty', 'Faulty')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending Approval', 'Pending Approval'), ('Not available', ' Not available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('VGA Cables', 'VGA Cables'), ('Others', 'Others'), ('Extension/Power Cables', 'Extension/Power Cables'), ('Remote', 'Remote'), ('HDMI Cables', 'HDMI Cables'), ('Projector', 'Projector')], max_length=50, verbose_name='Asset category name'),
        ),
        migrations.AlterField(
            model_name='borrowed_asset',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
