# Generated by Django 4.1.3 on 2023-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('assets', '0004_alter_asset_condition_alter_asset_status_and_more'),

    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',

            field=models.CharField(choices=[('Not Woking', 'Not Working'), ('Faulty', 'Faulty'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),

        ),
        migrations.AlterField(
            model_name='asset',
            name='status',

            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Available', 'Available'), ('Not available', ' Not available'), ('Pending Approval', 'Pending Approval')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Remote', 'Remote'), ('Projector', 'Projector'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Extension/Power Cables', 'Extension/Power Cables'), ('VGA Cables', 'VGA Cables'), ('HDMI Cables', 'HDMI Cables'), ('Others', 'Others')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
