# Generated by Django 4.1.3 on 2023-02-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_woring_quantity_assetcategory_working_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcategory',
            old_name='categoty_pic',
            new_name='category_pic',
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Faulty', 'Faulty'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', ' Not available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='borrowed_assets',
            field=models.PositiveIntegerField(default=0, verbose_name='number is assets that are borrowedd'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='number of assets available'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='working_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='number is assets that are working'),
        ),
    ]
