# Generated by Django 4.1.3 on 2023-07-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_borrowed_asset_picked_on_and_more'),
        ('assets', '0006_borrowed_asset_date_picked_on_alter_asset_condition_and_more'),
    ]

    operations = [
    ]
