# Generated by Django 4.1.3 on 2023-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_condition_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Faulty', 'Faulty'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Projector', 'Projector'), ('VGA Cables', 'VGA Cables'), ('HDMI Cables', 'HDMI Cables'), ('Remote', 'Remote'), ('Others', 'Others'), ('VGA-HDMI Converters', ' VGA-HDMI Converters')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
