# Generated by Django 4.1.3 on 2023-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_borrowed_asset_asset_status_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Not Woking', 'Not Working'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Borrowed', 'Borrowed'), ('Available', 'Available'), ('Pending Approval', 'Pending Approval')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Extension/Power Cables', 'Extension/Power Cables'), ('Projector', 'Projector'), ('Remote', 'Remote'), ('HDMI Cables', 'HDMI Cables'), ('VGA Cables', 'VGA Cables'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Others', 'Others')], max_length=50, verbose_name='Asset category name'),
        ),
        migrations.AlterField(
            model_name='borrowed_asset',
            name='asset_status',
            field=models.CharField(blank=True, choices=[('Pending Approval', 'Pending Approval'), ('Borrowed', 'Borrowed'), ('Returned', ' Returned')], max_length=50, null=True, verbose_name='state of the asset'),
        ),
        migrations.AlterField(
            model_name='borrowed_asset',
            name='date_picked_on',
            field=models.DateField(auto_now=True, verbose_name='date picked'),
        ),
    ]
