# Generated by Django 4.1.3 on 2023-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_condition_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Not Woking', 'Not Working'), ('Faulty', 'Faulty')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Others', 'Others'), ('Projector', 'Projector'), ('Extension/Power Cables', 'Extension/Power Cables'), ('Remote', 'Remote'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('VGA Cables', 'VGA Cables'), ('HDMI Cables', 'HDMI Cables')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
