# Generated by Django 4.1.3 on 2023-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_status_alter_assetcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Not Woking', 'Not Working'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Extension/Power Cables', 'Extension/Power Cables'), ('Others', 'Others'), ('HDMI Cables', 'HDMI Cables'), ('VGA Cables', 'VGA Cables'), ('Projector', 'Projector'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Remote', 'Remote')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
