# Generated by Django 4.1.3 on 2023-01-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_scale'),
        ('assets', '0010_alter_asset_condition_alter_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowd_asset',
            old_name='persion',
            new_name='person',
        ),
        migrations.AddField(
            model_name='borrowd_asset',
            name='organization',
            field=models.ForeignKey(default='Egesa', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='lab / organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Not Woking', 'Not Working'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
    ]
