# Generated by Django 4.1.3 on 2023-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_condition_alter_asset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategory',
            name='borrowed_assets',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='category_pic',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='working_quantity',
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Available', 'Available'), ('Not available', ' Not available')], max_length=50, verbose_name='asset status'),
        ),
    ]
