# Generated by Django 4.1.3 on 2023-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_assetcategory_borrowed_assets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Faulty', 'Faulty'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Borrowed', 'Borrowed'), ('Available', 'Available')], max_length=50, verbose_name='asset status'),
        ),
    ]
