# Generated by Django 4.1.3 on 2023-07-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_asset_condition_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Available', 'Available'), ('Not available', ' Not available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Projector', 'Projector'), ('Remote', 'Remote'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('HDMI Cables', 'HDMI Cables'), ('Others', 'Others'), ('VGA Cables', 'VGA Cables'), ('Extension/Power Cables', 'Extension/Power Cables')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
