# Generated by Django 4.1.3 on 2023-02-02 10:42

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_issue_status'),
        ('assets', '0012_remove_assetcategory_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='borrowed_assets',
            field=models.PositiveIntegerField(default=0, verbose_name='number is assets that are borrowedd'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Projector', 'Projector'), ('HDMI Cables', 'HDMI Cables'), ('Others', 'Others'), ('VGA Cables', 'VGA Cables'), ('VGA-HDMI Converters', ' VGA-HDMI Converters')], default='Projector', max_length=50, verbose_name='Asset category name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='category_pic',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.asset_categorty_photo_upload, verbose_name='Category image'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='lab / organization'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='number of assets available'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='working_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='number is assets that are working'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Not available', ' Not available'), ('Available', 'Available')], max_length=50, verbose_name='asset status'),
        ),
    ]
