# Generated by Django 4.1.3 on 2023-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_asset_category_type_alter_asset_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Borrowed', 'Borrowed'), ('Available', 'Available')], max_length=50, verbose_name='asset status'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('VGA Cables', 'VGA Cables'), ('Projector', 'Projector'), ('HDMI Cables', 'HDMI Cables'), ('Others', 'Others')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
