# Generated by Django 4.1.3 on 2023-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_asset_condition_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Faulty', 'Faulty'), ('Good', 'Good'), ('Not Woking', 'Not Working')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='category',
            field=models.TextField(choices=[('Projector', 'Projector'), ('VGA-HDMI Converters', ' VGA-HDMI Converters'), ('Others', 'Others'), ('HDMI Cables', 'HDMI Cables'), ('VGA Cables', 'VGA Cables')], max_length=50, verbose_name='Asset category name'),
        ),
    ]
