# Generated by Django 4.1.3 on 2023-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_alter_asset_condition_alter_asset_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowd_asset',
            options={'ordering': ['-returned_on'], 'verbose_name': 'Borrowd Asset', 'verbose_name_plural': 'Borrowd Assets'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Not Woking', 'Not Working'), ('Faulty', 'Faulty'), ('Good', 'Good')], max_length=50, verbose_name='asset condition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', ' Not available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
    ]
