# Generated by Django 4.1.3 on 2023-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_alter_asset_condition_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Not available', ' Not available'), ('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, verbose_name='asset status'),
        ),
    ]
