# Generated by Django 4.1.3 on 2022-12-10 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Organization's ID")),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization name')),
                ('scale', models.CharField(choices=[('medium scale', 'medium scale'), ('Small scale', 'Small scale'), ('personal venture', 'personal venture')], max_length=50, verbose_name='Scale of organization')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name="Organization's creater")),
            ],
        ),
    ]
