# Generated by Django 4.1.3 on 2022-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='scale',
            field=models.CharField(choices=[('medium scale', 'medium scale'), ('Small scale', 'Small scale'), ('personal venture', 'personal venture')], max_length=50, verbose_name='Scale of organization'),
        ),
    ]
