# Generated by Django 4.1.3 on 2023-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Argent', 'Argent'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=50, verbose_name='state'),
        ),
    ]
