# Generated by Django 4.1.3 on 2023-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Argent', 'Argent'), ('Done', 'Done'), ('Pending', 'Pending')], max_length=50, verbose_name='state'),
        ),
    ]
