# Generated by Django 4.1.3 on 2023-05-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_user'),
        ('organizations', '0009_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='test default', max_length=50, verbose_name='title of the field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Argent', 'Argent')], max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.account', verbose_name="Organization's creater"),
        ),
    ]
