# Generated by Django 4.1.3 on 2023-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_issue_title_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='admin_responses',
            field=models.TextField(blank=True, null=True, verbose_name='admins responses '),
        ),
        migrations.AlterField(
            model_name='issue',
            name='details',
            field=models.TextField(max_length=400, verbose_name='issue details'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Noted pending address', 'Noted pending address'), ('Adressing', 'Adressing'), ('Urgent attention', 'Urgent attention'), ('Low attention', 'Low attention'), ('Done', 'Done'), ('Medium attention', 'Medium attention')], max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title of the field'),
        ),
    ]
