# Generated by Django 4.1.3 on 2023-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_issue_admin_responses_alter_issue_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Urgent attention', 'Urgent attention'), ('Addressing', 'Addressing'), ('Done', 'Done'), ('Low attention', 'Low attention'), ('Medium attention', 'Medium attention'), ('Noted pending address', 'Noted pending address')], max_length=50, verbose_name='state'),
        ),
    ]
