# Generated by Django 4.1.3 on 2023-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='admin_responses',
            new_name='admin_response',
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Low attention', 'Low attention'), ('Medium attention', 'Medium attention'), ('Urgent attention', 'Urgent attention'), ('Addressing', 'Addressing'), ('Noted pending address', 'Noted pending address')], max_length=50, verbose_name='state'),
        ),
    ]
