# Generated by Django 4.1.3 on 2023-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_rename_admin_responses_issue_admin_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Urgent attention', 'Urgent attention'), ('Addressing', 'Addressing'), ('Low attention', 'Low attention'), ('Noted pending address', 'Noted pending address'), ('Medium attention', 'Medium attention'), ('Done', 'Done')], max_length=50, verbose_name='state'),
        ),
    ]
