# Generated by Django 4.1.3 on 2023-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_issue_status_alter_organization_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['reported_on'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('personal venture', 'personal venture'), ('Small scale', 'Small scale'), ('medium scale', 'medium scale')], max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='scale',
            field=models.CharField(choices=[('Argent', 'Argent'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=50, verbose_name='Scale of organization'),
        ),
    ]
