# Generated by Django 4.1.3 on 2023-01-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_alter_issue_organization_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='organization/lab'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Argent', 'Argent'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=50, verbose_name='state'),
        ),
    ]
