# Generated by Django 4.1.3 on 2023-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_issue_reported_by_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Argent', 'Argent'), ('Pending', 'Pending')], max_length=50, verbose_name='state'),
        ),
    ]
