# Generated by Django 4.1.3 on 2023-06-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='day1',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day2',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day3',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day4',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day5',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day6',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=15, null=True),
        ),
    ]
