# Generated by Django 4.1.3 on 2023-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_userrole_day1_alter_userrole_day2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='day1',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Thurday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day2',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Thurday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day3',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Thurday', 'Thursday')], max_length=15, null=True),
=======
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Thurday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=15, null=True),
>>>>>>> 76a24c3cb4c0e52ba96a0e3d1aa056cc359af091
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day4',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Thurday', 'Thursday')], max_length=15, null=True),
=======
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Thurday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=15, null=True),
>>>>>>> 76a24c3cb4c0e52ba96a0e3d1aa056cc359af091
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day5',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Thurday', 'Thursday')], max_length=15, null=True),
=======
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Thurday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=15, null=True),
>>>>>>> 76a24c3cb4c0e52ba96a0e3d1aa056cc359af091
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day6',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Thurday', 'Thursday')], max_length=15, null=True),
=======
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Thurday', 'Thursday'), ('Tuesday', 'Tuesday')], max_length=15, null=True),
>>>>>>> 76a24c3cb4c0e52ba96a0e3d1aa056cc359af091
        ),
    ]
