# Generated by Django 4.1.3 on 2023-05-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_user'),
        ('roles', '0007_alter_userrole_day1_alter_userrole_day2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserRole', to='accounts.account', verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day1',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day2',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day3',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day4',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day5',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day6',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Thurday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=15, null=True),
        ),
    ]
