# Generated by Django 4.1.3 on 2023-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_alter_userrole_assigned_to_alter_userrole_day1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='day1',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thurday', 'Thursday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day2',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thurday', 'Thursday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day3',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thurday', 'Thursday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day4',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thurday', 'Thursday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day5',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thurday', 'Thursday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='day6',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thurday', 'Thursday')], max_length=15, null=True),
        ),
    ]
