# Generated by Django 4.1.3 on 2023-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0002_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Medium attention', 'Medium attention'), ('Addressing', 'Addressing'), ('Noted pending address', 'Noted pending address'), ('Low attention', 'Low attention'), ('Done', 'Done'), ('Urgent attention', 'Urgent attention')], max_length=50, verbose_name='state'),
        ),
    ]
