# Generated by Django 4.1.3 on 2023-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0003_alter_issue_status_alter_lab_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Noted pending address', 'Noted pending address'), ('Low attention', 'Low attention'), ('Addressing', 'Addressing'), ('Medium attention', 'Medium attention'), ('Done', 'Done'), ('Urgent attention', 'Urgent attention')], max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Lab name'),
        ),
    ]
