# Generated by Django 4.1.3 on 2023-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0004_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Addressing', 'Addressing'), ('Noted pending address', 'Noted pending address'), ('Urgent attention', 'Urgent attention'), ('Medium attention', 'Medium attention'), ('Low attention', 'Low attention'), ('Done', 'Done')], max_length=50, verbose_name='state'),
        ),
    ]
