# Generated by Django 4.1.3 on 2023-07-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0004_alter_issue_status_alter_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Medium attention', 'Medium attention'), ('Addressing', 'Addressing'), ('Done', 'Done'), ('Low attention', 'Low attention'), ('Noted pending address', 'Noted pending address'), ('Urgent attention', 'Urgent attention')], max_length=50, verbose_name='state'),
        ),
    ]
