# Generated by Django 4.1.3 on 2023-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0005_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Medium attention', 'Medium attention'), ('Urgent attention', 'Urgent attention'), ('Done', 'Done'), ('Low attention', 'Low attention'), ('Noted pending address', 'Noted pending address'), ('Addressing', 'Addressing')], max_length=50, verbose_name='state'),
        ),
    ]
