# Generated by Django 4.1.3 on 2023-06-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0006_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Urgent attention', 'Urgent attention'), ('Medium attention', 'Medium attention'), ('Low attention', 'Low attention'), ('Addressing', 'Addressing'), ('Done', 'Done'), ('Noted pending address', 'Noted pending address')], max_length=50, verbose_name='state'),
        ),
    ]
