# Generated by Django 4.1.3 on 2023-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0007_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Addressing', 'Addressing'), ('Low attention', 'Low attention'), ('Noted pending address', 'Noted pending address'), ('Done', 'Done'), ('Medium attention', 'Medium attention'), ('Urgent attention', 'Urgent attention')], max_length=50, verbose_name='state'),
        ),
    ]
