# Generated by Django 4.1.3 on 2023-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0011_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Noted pending address', 'Noted pending address'), ('Urgent attention', 'Urgent attention'), ('Done', 'Done'), ('Addressing', 'Addressing'), ('Medium attention', 'Medium attention'), ('Low attention', 'Low attention')], max_length=50, verbose_name='state'),
        ),
    ]
